import { API_ROUTE } from "./api.shared";

export const PRODUCT_ROUTE = "/product";

export const SEARCH_PRODUCT_ROUTE = "/search";
export const ORDER_PRODUCT_ROUTE = "/order";
export const SEARCH_RANDOM_PRODUCT_ROUTE = "/random";

export const SEARCH_PRODUCT_API = API_ROUTE + PRODUCT_ROUTE + SEARCH_PRODUCT_ROUTE;
export const ORDER_PRODUCT_API = API_ROUTE + PRODUCT_ROUTE + ORDER_PRODUCT_ROUTE;
export const SEARCH_RANDOM_PRODUCT_API = API_ROUTE + PRODUCT_ROUTE + SEARCH_RANDOM_PRODUCT_ROUTE;
